### ISSUE TITLE
Make toml specified write range params configurable

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-statediff-service#43]
E.g.

```toml
intermediateStateNodes = true
intermediateStorageNodes = true
includeBlock = true
includeReceipts = true
includeTD = true
includeCode = true
watchedAddresses = []
watchedStorageKeys = []
```
